### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined 

### ISSUE THREAD

**Issue by jrieken** [austin-----/code-gnu-global#17]
```
TypeError: Cannot read property 'toString' of undefined 
at \austin.code-gnu-global-0.2.0\out\src\features\completionItemProvider.js:38:19 
at _fulfilled (\austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:834:54) 
at self.promiseDispatch.done (\austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:863:30) 
at Promise.promise.promiseDispatch (\austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:796:13) 
at \austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:604:44 
at runSingle (\austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:137:13) 
at flush (\austin.code-gnu-global-0.2.0\node_modules\child-process-promise\node_modules\q\q.js:125:13) 
at doNTCallback0 (node.js:420:9) 
at process._tickCallback (node.js:349:13) 
```

**Comment by austin-----** [comment]
Fixed in 0.2.1
