### ISSUE TITLE
No symbol information, error in the console

### ISSUE THREAD

**Issue by ricardopieper** [austin-----/code-gnu-global#5]
I have 2 very simple source files:
main.cpp, includes aux.cpp
aux.cpp, has a function `int sum (int a, int b)`

G++ compiles it correcly.
`gtags` generates some files
`global -c` outputs "main" and "sum", seems to be working fine.

But when I try to use the "@" command, it says "Unfortunately we have no symbol information for the file".

In the console, it says this:

    Activating extension `austin.code-gnu-global` failed: Cannot find module './features/completionItemProvider'.

WIth the following error stack:

     at Function.Module._resolveFilename (module.js:336:15)
     at Function.Module._load (module.js:286:25)
     at Function.O.n._load (/usr/local/bin/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:18:17333)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
     at Object.<anonymous> (/home/ricardo/.vscode/extensions/austin.code-gnu-global/out/src/extension.js:5:32)
     at Module._compile (module.js:434:26)
     at Object.Module._extensions..js (module.js:452:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)

Any idea on what is going wrong? I haven't took a look at the plugin code yet.

**Comment by austin-----** [comment]
It looks like a case sensitivity issue on Linux. The package apparently has the is file with an upper case file name. Will roll out a fix soon.

**Comment by austin-----** [comment]
Duplicate as #4
